name: Sync origin

on:
  schedule:
  - cron:  "*/15 * * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync-master
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "home-assistant/home-assistant"
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: repo-sync-dev
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "home-assistant/home-assistant"
        source_branch: "dev"
        destination_branch: "dev"
        github_token: ${{ secrets.GITHUB_TOKEN }}
